"""add IOC, ReportIOC, ReportMispEvent, MISPSettings tables

Revision ID: 0e700e26e87f
Revises: d38850006560
Create Date: 2026-06-21 20:26:08.040776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # SQLModel renders columns as sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = '0e700e26e87f'
down_revision: Union[str, Sequence[str], None] = 'd38850006560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_IOC_TYPE = sa.Enum('IP_SRC', 'IP_DST', 'DOMAIN', 'HOSTNAME', 'URL', 'MD5', 'SHA1', 'SHA256', 'EMAIL', 'FILENAME', 'CVE', name='ioctype')


def _ioc_type(bind):
    if bind.dialect.name == 'postgresql':
        return postgresql.ENUM('IP_SRC', 'IP_DST', 'DOMAIN', 'HOSTNAME', 'URL', 'MD5', 'SHA1', 'SHA256', 'EMAIL', 'FILENAME', 'CVE', name='ioctype', create_type=False)
    return sa.Enum('IP_SRC', 'IP_DST', 'DOMAIN', 'HOSTNAME', 'URL', 'MD5', 'SHA1', 'SHA256', 'EMAIL', 'FILENAME', 'CVE', name='ioctype')


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    _IOC_TYPE.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mispsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('default_distribution', sa.Integer(), nullable=False),
    sa.Column('default_threat_level', sa.Integer(), nullable=False),
    sa.Column('default_published', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ioc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('ioc_type', _ioc_type(bind), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ioc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ioc_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ioc_source_id'), ['source_id'], unique=False)

    op.create_table('reportmispevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('event_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attribute_count', sa.Integer(), nullable=False),
    sa.Column('last_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', name='uq_mispevent_report')
    )
    with op.batch_alter_table('reportmispevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reportmispevent_report_id'), ['report_id'], unique=False)

    op.create_table('reportioc',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ioc_id'], ['ioc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'ioc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportioc')
    with op.batch_alter_table('reportmispevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reportmispevent_report_id'))

    op.drop_table('reportmispevent')
    with op.batch_alter_table('ioc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ioc_source_id'))
        batch_op.drop_index(batch_op.f('ix_ioc_notebook_id'))

    op.drop_table('ioc')
    op.drop_table('mispsettings')
    _IOC_TYPE.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
