"""initial schema

Revision ID: 11f71f3875b9
Revises: 
Create Date: 2026-06-13 14:21:59.167342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # SQLModel renders columns as sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = '11f71f3875b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# SQLite FTS5 search objects (report_fts virtual table + sync triggers). Frozen
# copies of services/search.py's runtime DDL — a baseline migration must be
# immutable, so it does NOT import the live constant. They are kept identical so
# a fresh `upgrade head` yields the same searchable schema the create_all path
# (services/search.py register_fts_events) builds. The report_fts* tables are
# excluded from autogenerate in env.py.
_FTS_DDL = [
    "CREATE VIRTUAL TABLE IF NOT EXISTS report_fts "
    "USING fts5(title, body_md, key_judgements, key_assumptions, intelligence_gaps, "
    "content='report', content_rowid='id')",
    """CREATE TRIGGER IF NOT EXISTS report_ai AFTER INSERT ON report BEGIN
        INSERT INTO report_fts(rowid, title, body_md, key_judgements, key_assumptions, intelligence_gaps)
        VALUES (new.id, new.title, new.body_md, new.key_judgements, new.key_assumptions, new.intelligence_gaps);
    END""",
    """CREATE TRIGGER IF NOT EXISTS report_ad AFTER DELETE ON report BEGIN
        INSERT INTO report_fts(report_fts, rowid, title, body_md, key_judgements, key_assumptions, intelligence_gaps)
        VALUES('delete', old.id, old.title, old.body_md, old.key_judgements, old.key_assumptions, old.intelligence_gaps);
    END""",
    """CREATE TRIGGER IF NOT EXISTS report_au AFTER UPDATE ON report BEGIN
        INSERT INTO report_fts(report_fts, rowid, title, body_md, key_judgements, key_assumptions, intelligence_gaps)
        VALUES('delete', old.id, old.title, old.body_md, old.key_judgements, old.key_assumptions, old.intelligence_gaps);
        INSERT INTO report_fts(rowid, title, body_md, key_judgements, key_assumptions, intelligence_gaps)
        VALUES (new.id, new.title, new.body_md, new.key_judgements, new.key_assumptions, new.intelligence_gaps);
    END""",
]

# PostgreSQL native ENUMs are schema objects, not table-owned columns.  The
# baseline owns every type it introduces: create each once before creating its
# tables and drop it only after the final table has gone on downgrade.  Column
# definitions reference those types with ``create_type=False`` so repeated uses
# (for example ``intellevel``) never attempt a duplicate CREATE TYPE.
_ENUMS = (
    sa.Enum('ACTOR', 'CAMPAIGN', 'MALWARE', 'TECHNIQUE', 'SECTOR', 'TOPIC', name='tagkind'),
    sa.Enum('ADMIN', 'ANALYST', 'REVIEWER', 'STAKEHOLDER', name='role'),
    sa.Enum('STRATEGIC', 'TACTICAL', 'OPERATIONAL', name='intellevel'),
    sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'),
    sa.Enum('OPEN', 'IN_PROGRESS', 'SATISFIED', 'CLOSED', name='requirementstatus'),
    sa.Enum('LOW', 'MODERATE', 'HIGH', name='diamondconfidence'),
    sa.Enum('RED', 'AMBER_STRICT', 'AMBER', 'GREEN', 'CLEAR', name='tlp'),
    sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'PUBLISHED', name='reportstatus'),
    sa.Enum('FULL', 'EXEC_BRIEF', 'ONE_PAGER', name='productformat'),
)


def _enum_type(bind, name: str, *values: str):
    if bind.dialect.name == 'postgresql':
        return postgresql.ENUM(*values, name=name, create_type=False)
    return sa.Enum(*values, name=name)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    for enum in _ENUMS:
        enum.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', _enum_type(bind, 'tagkind', 'ACTOR', 'CAMPAIGN', 'MALWARE', 'TECHNIQUE', 'SECTOR', 'TOPIC'), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'slug', name='uq_tag_kind_slug')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_slug'), ['slug'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', _enum_type(bind, 'role', 'ADMIN', 'ANALYST', 'REVIEWER', 'STAKEHOLDER'), nullable=False),
    sa.Column('preferred_intel_level', _enum_type(bind, 'intellevel', 'STRATEGIC', 'TACTICAL', 'OPERATIONAL'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sub'), ['sub'], unique=True)

    op.create_table('notebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notebook', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notebook_owner_id'), ['owner_id'], unique=False)

    op.create_table('requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stakeholder_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intel_level', _enum_type(bind, 'intellevel', 'STRATEGIC', 'TACTICAL', 'OPERATIONAL'), nullable=False),
    sa.Column('priority', _enum_type(bind, 'priority', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'), nullable=False),
    sa.Column('status', _enum_type(bind, 'requirementstatus', 'OPEN', 'IN_PROGRESS', 'SATISFIED', 'CLOSED'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_stakeholder_id'), ['stakeholder_id'], unique=False)

    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_notebook_id'), ['notebook_id'], unique=False)

    op.create_table('diamondmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adversary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capability', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('infrastructure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('victim', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', _enum_type(bind, 'diamondconfidence', 'LOW', 'MODERATE', 'HIGH'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diamondmodel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diamondmodel_notebook_id'), ['notebook_id'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('body_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_notebook_id'), ['notebook_id'], unique=False)

    op.create_table('notebookrequirement',
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notebook_id', 'requirement_id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_judgements', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_assumptions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intelligence_gaps', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intel_level', _enum_type(bind, 'intellevel', 'STRATEGIC', 'TACTICAL', 'OPERATIONAL'), nullable=False),
    sa.Column('tlp', _enum_type(bind, 'tlp', 'RED', 'AMBER_STRICT', 'AMBER', 'GREEN', 'CLEAR'), nullable=False),
    sa.Column('status', _enum_type(bind, 'reportstatus', 'DRAFT', 'IN_REVIEW', 'APPROVED', 'PUBLISHED'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_notebook_id'), ['notebook_id'], unique=False)

    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_notebook_id'), ['notebook_id'], unique=False)

    op.create_table('disseminationevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('stakeholder_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disseminationevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disseminationevent_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disseminationevent_stakeholder_id'), ['stakeholder_id'], unique=False)

    op.create_table('renderedproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('format', _enum_type(bind, 'productformat', 'FULL', 'EXEC_BRIEF', 'ONE_PAGER'), nullable=False),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rendered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('renderedproduct', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_renderedproduct_report_id'), ['report_id'], unique=False)

    op.create_table('reportattachment',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'attachment_id')
    )
    op.create_table('reportrequirement',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'requirement_id')
    )
    op.create_table('reportsource',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'source_id')
    )
    op.create_table('reporttag',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'tag_id')
    )
    # ### end Alembic commands ###

    # Full-text search index (SQLite only; other backends skip search indexing).
    if op.get_bind().dialect.name == "sqlite":
        for stmt in _FTS_DDL:
            op.execute(stmt)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the FTS objects first — their triggers depend on the report table.
    if op.get_bind().dialect.name == "sqlite":
        for trigger in ("report_au", "report_ad", "report_ai"):
            op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
        op.execute("DROP TABLE IF EXISTS report_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporttag')
    op.drop_table('reportsource')
    op.drop_table('reportrequirement')
    op.drop_table('reportattachment')
    with op.batch_alter_table('renderedproduct', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_renderedproduct_report_id'))

    op.drop_table('renderedproduct')
    with op.batch_alter_table('disseminationevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disseminationevent_stakeholder_id'))
        batch_op.drop_index(batch_op.f('ix_disseminationevent_report_id'))

    op.drop_table('disseminationevent')
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_notebook_id'))

    op.drop_table('source')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_notebook_id'))

    op.drop_table('report')
    op.drop_table('notebookrequirement')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_notebook_id'))

    op.drop_table('note')
    with op.batch_alter_table('diamondmodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diamondmodel_notebook_id'))

    op.drop_table('diamondmodel')
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_notebook_id'))

    op.drop_table('attachment')
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_stakeholder_id'))

    op.drop_table('requirement')
    with op.batch_alter_table('notebook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notebook_owner_id'))

    op.drop_table('notebook')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sub'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_slug'))
        batch_op.drop_index(batch_op.f('ix_tag_kind'))

    op.drop_table('tag')
    for enum in reversed(_ENUMS):
        enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
