"""entity relationships

Revision ID: 8db5b15e1537
Revises: b3d9a4e21c7f
Create Date: 2026-06-16 20:11:35.625352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8db5b15e1537'
down_revision: Union[str, Sequence[str], None] = 'b3d9a4e21c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RELATION_VALUES = ('USES', 'ATTRIBUTED_TO', 'VARIANT_OF', 'TARGETS', 'RELATED_TO')
_RELATION_TYPE = sa.Enum(*_RELATION_VALUES, name='relationtype')


def _relation_type(bind):
    if bind.dialect.name == 'postgresql':
        return postgresql.ENUM(*_RELATION_VALUES, name='relationtype', create_type=False)
    return sa.Enum(*_RELATION_VALUES, name='relationtype')


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    _RELATION_TYPE.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entityrelationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_tag_id', sa.Integer(), nullable=False),
    sa.Column('target_tag_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', _relation_type(bind), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_tag_id', 'target_tag_id', 'relation_type', name='uq_entity_relationship')
    )
    with op.batch_alter_table('entityrelationship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entityrelationship_source_tag_id'), ['source_tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entityrelationship_target_tag_id'), ['target_tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entityrelationship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entityrelationship_target_tag_id'))
        batch_op.drop_index(batch_op.f('ix_entityrelationship_source_tag_id'))

    op.drop_table('entityrelationship')
    _RELATION_TYPE.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
