"""report analytic_confidence

Revision ID: 97f13b59967e
Revises: f6b4f974b72e
Create Date: 2026-06-15 20:26:07.780376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f13b59967e'
down_revision: Union[str, Sequence[str], None] = 'f6b4f974b72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analytic_confidence', sa.Enum('LOW', 'MODERATE', 'HIGH', name='analyticconfidence'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('analytic_confidence')

    # ### end Alembic commands ###
