"""add ach model

Revision ID: b232d8f39c4b
Revises: 8db5b15e1537
Create Date: 2026-06-16 20:52:32.613739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel renders columns as sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = 'b232d8f39c4b'
down_revision: Union[str, Sequence[str], None] = '8db5b15e1537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hypotheses', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('evidence', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('ratings', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achmodel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achmodel_notebook_id'), ['notebook_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achmodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achmodel_notebook_id'))

    op.drop_table('achmodel')
    # ### end Alembic commands ###
