"""add audit event and settings

Revision ID: b2c5de1928db
Revises: bec17a603c91
Create Date: 2026-06-20 18:00:35.444204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # SQLModel renders columns as sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = 'b2c5de1928db'
down_revision: Union[str, Sequence[str], None] = 'bec17a603c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ENUMS = (
    sa.Enum('INFO', 'WARNING', 'CRITICAL', name='auditseverity'),
    sa.Enum('AUTHENTICATION', 'AUTHORIZATION', 'LIFECYCLE', 'ADMIN', 'DATA_ACCESS', 'DISSEMINATION', 'SYSTEM', name='auditcategory'),
    sa.Enum('SUCCESS', 'FAILURE', name='auditoutcome'),
)


def _enum_type(bind, enum):
    if bind.dialect.name == 'postgresql':
        return postgresql.ENUM(*enum.enums, name=enum.name, create_type=False)
    return sa.Enum(*enum.enums, name=enum.name)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    for enum in _ENUMS:
        enum.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('methods', sa.JSON(), server_default='["stdout"]', nullable=False),
    sa.Column('min_severity', _enum_type(bind, _ENUMS[0]), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('syslog_host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('syslog_port', sa.Integer(), nullable=False),
    sa.Column('syslog_protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('syslog_facility', sa.Integer(), nullable=False),
    sa.Column('http_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('http_verify_tls', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', _enum_type(bind, _ENUMS[1]), nullable=False),
    sa.Column('severity', _enum_type(bind, _ENUMS[0]), nullable=False),
    sa.Column('outcome', _enum_type(bind, _ENUMS[2]), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sa.JSON(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditevent_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_severity'), ['severity'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditevent_severity'))
        batch_op.drop_index(batch_op.f('ix_auditevent_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_auditevent_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_auditevent_actor_id'))
        batch_op.drop_index(batch_op.f('ix_auditevent_action'))

    op.drop_table('auditevent')
    op.drop_table('auditsettings')
    for enum in reversed(_ENUMS):
        enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
