"""tag attribution profile

Revision ID: b3d9a4e21c7f
Revises: c5c560ff65be
Create Date: 2026-06-15 21:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel renders string columns as sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = 'b3d9a4e21c7f'
down_revision: Union[str, Sequence[str], None] = 'c5c560ff65be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspected_attribution', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('motivations', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('first_seen', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('last_seen', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('first_seen')
        batch_op.drop_column('motivations')
        batch_op.drop_column('suspected_attribution')

    # ### end Alembic commands ###
