"""add product feedback

Revision ID: bec17a603c91
Revises: a1f0c2d3e4b5
Create Date: 2026-06-20 16:12:09.554488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # SQLModel renders columns as sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = 'bec17a603c91'
down_revision: Union[str, Sequence[str], None] = 'a1f0c2d3e4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ENUMS = (
    sa.Enum('NOT_USEFUL', 'USEFUL', 'HIGHLY_USEFUL', name='productusefulness'),
    sa.Enum('MET', 'PARTIALLY_MET', 'NOT_MET', name='rfisatisfaction'),
)


def _enum_type(bind, enum):
    if bind.dialect.name == 'postgresql':
        return postgresql.ENUM(*enum.enums, name=enum.name, create_type=False)
    return sa.Enum(*enum.enums, name=enum.name)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    for enum in _ENUMS:
        enum.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('stakeholder_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('usefulness', _enum_type(bind, _ENUMS[0]), nullable=False),
    sa.Column('satisfaction', _enum_type(bind, _ENUMS[1]), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'stakeholder_id', name='uq_feedback_report_stakeholder')
    )
    with op.batch_alter_table('productfeedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productfeedback_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_productfeedback_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_productfeedback_stakeholder_id'), ['stakeholder_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productfeedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productfeedback_stakeholder_id'))
        batch_op.drop_index(batch_op.f('ix_productfeedback_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_productfeedback_report_id'))

    op.drop_table('productfeedback')
    for enum in reversed(_ENUMS):
        enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
