"""proxy settings table

Revision ID: d38850006560
Revises: 27b21ab9c6aa
Create Date: 2026-06-21 17:13:01.279949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # SQLModel renders columns as sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = 'd38850006560'
down_revision: Union[str, Sequence[str], None] = '27b21ab9c6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PROXY_MODE = sa.Enum('NONE', 'SYSTEM', 'EXPLICIT', name='proxymode')


def _proxy_mode_type(bind):
    if bind.dialect.name == 'postgresql':
        return postgresql.ENUM('NONE', 'SYSTEM', 'EXPLICIT', name='proxymode', create_type=False)
    return sa.Enum('NONE', 'SYSTEM', 'EXPLICIT', name='proxymode')


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    _PROXY_MODE.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxysettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', _proxy_mode_type(bind), nullable=False),
    sa.Column('proxy_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('no_proxy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxysettings')
    _PROXY_MODE.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
