"""proxy settings table

Revision ID: d38850006560
Revises: 27b21ab9c6aa
Create Date: 2026-06-21 17:13:01.279949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel renders columns as sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = 'd38850006560'
down_revision: Union[str, Sequence[str], None] = '27b21ab9c6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxysettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('NONE', 'SYSTEM', 'EXPLICIT', name='proxymode'), nullable=False),
    sa.Column('proxy_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('no_proxy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxysettings')
    # ### end Alembic commands ###
