"""requirement kinds

Revision ID: dfb25674e675
Revises: b232d8f39c4b
Create Date: 2026-06-19 18:20:24.694481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel renders columns as sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = 'dfb25674e675'
down_revision: Union[str, Sequence[str], None] = 'b232d8f39c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (kind='RFI', decision_context='');
    # PIR/GIR/RFI is the FR #42 requirement-kind taxonomy. review_by is nullable
    # (only PIRs carry a review date), so it needs no server_default.
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.Enum('PIR', 'GIR', 'RFI', name='requirementkind'), server_default='RFI', nullable=False))
        batch_op.add_column(sa.Column('decision_context', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('review_by', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_requirement_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_kind'))
        batch_op.drop_column('review_by')
        batch_op.drop_column('decision_context')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
