"""add figure table

Notebook figures: uploaded images (PNG/JPEG/GIF) embedded inline into reports via
the ``[[figure:ID]]`` token. Like ``DiamondModel`` there is no report-link table —
the token is the association, resolved at render time. See ``services/figures.py``.

Revision ID: f6b4f974b72e
Revises: 8a7c1b2d4e5f
Create Date: 2026-06-14 15:32:39.609277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel renders columns as sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = 'f6b4f974b72e'
down_revision: Union[str, Sequence[str], None] = '8a7c1b2d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('figure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('figure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_figure_notebook_id'), ['notebook_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('figure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_figure_notebook_id'))

    op.drop_table('figure')
    # ### end Alembic commands ###
